// From Sebastian Lague github: https://github.com/SebLague/Fluid-Sim/blob/Episode-01/Assets/Scripts/Compute%20Helpers/GPU%20Sort/Resources/BitonicMergeSort.compute
// Compute shader used to sort the spatial lookup table
#include "/Engine/Private/Common.ush"

static const int NumThreads = 128;

RWStructuredBuffer<uint3> Entries; //uint3(index, hash, key)
RWStructuredBuffer<uint> Offsets;
const uint numEntries;
const uint groupWidth;
const uint groupHeight;
const uint stepIndex;

[numthreads(NumThreads, 1, 1)]
void Sort (uint3 id : SV_DispatchThreadID)
{
	uint i = id.x;

	uint hIndex = i & (groupWidth - 1);
	uint indexLeft = hIndex + (groupHeight + 1) * (i / groupWidth);
	uint rightStepSize = stepIndex == 0 ? groupHeight - 2 * hIndex : (groupHeight + 1) / 2;
	uint indexRight = indexLeft + rightStepSize;

	// Exit if out of bounds (for non-power of 2 input sizes)
	if (indexRight >= numEntries) return;

	uint valueLeft = Entries[indexLeft].z;
	uint valueRight = Entries[indexRight].z;

	// Swap entries if value is descending
	if (valueLeft > valueRight)
	{
		uint3 temp = Entries[indexLeft];
		Entries[indexLeft] = Entries[indexRight];
		Entries[indexRight] = temp;
	}
}

[numthreads(NumThreads, 1, 1)]
void CalculateOffsets(uint3 id : SV_DispatchThreadID)
{
	if (id.x >= numEntries) { return; }

	uint i = id.x;
	uint null = numEntries;

	uint key = Entries[i].z;
	uint keyPrev = i == 0 ? null : Entries[i - 1].z;

	if (key != keyPrev)
	{
		Offsets[key] = i;
	}
}