#include "/Engine/Public/Platform.ush"
#include "/Engine/Private/Common.ush"

#include "/Shaders/Compute/Headers/SpatialHash3D.ush"
#include "/Shaders/Compute/Headers/SmoothingKernels.ush"

struct FFluidVolume {
    // Volume Data
    float3 BoundsPosition;
    float3 BoundsSize;
    
};

struct FFluidVolumeLocal {
    // Volume Data
    float3 MinBounds;  // Min Bounds
    float3 MaxBounds;  // Max Bounds    
};

ConstantBuffer<FFluidVolume> FluidVolume;
ConstantBuffer<FFluidVolumeLocal> Bounds;


StructuredBuffer<float3> Positions;
StructuredBuffer<float3> PredictedPositions;
StructuredBuffer<uint3> SpatialIndices; //uint3(index, hash, key)
StructuredBuffer<uint> SpatialOffsets;
uint NumParticles;

RWTexture3D<float> DensityMap;
uint3 DensityMapSize;

static const float spikyPow2 = 15 / (2 * PI * pow(4.0, 5));

bool SphereIntersect(float3 dist, float3 radius)
{
    float sqrDistance = dist*dist;
    return radius*radius > sqrDistance;
}

bool SphereIntersect(float3 dist, float3 radius)
{
    float sqrDistance = dist*dist;
    return radius*radius > sqrDistance;
}

float Density(float3 UVW)
{
    float density = 0;
    for (int i = 0; i < NumParticles; i++) 
    {
        float3 against = Positions[i];
        float3 offset = (UVW - against);
        float dist = sqrt(dot(offset, offset));

        if(SphereIntersect(dist, 4.0))
        {   
            density += SmoothingKernel(dist, 4.0) * 10.0;
        }
    }
    return density;
}


[numthreads(THREADS_X, THREADS_Y, THREADS_Z)]
void Compute(
	uint3 DispatchThreadId : SV_DispatchThreadID,
	uint GroupIndex : SV_GroupIndex)
{    
    if (DispatchThreadId.x >= DensityMapSize.x || 
        DispatchThreadId.y >= DensityMapSize.y || 
        DispatchThreadId.z >= DensityMapSize.z)
        return;

    float3 UVW = (float3(DispatchThreadId)) / DensityMapSize;
    float3 Position = (UVW - 0.5) * (Bounds.MaxBounds * 2.0);
    float density = Density(Position);

    DensityMap[DispatchThreadId] = density;
}