#include "/Engine/Public/Platform.ush"
#include "/Engine/Private/Common.ush"

#include "/Shaders/Compute/Headers/Common.ush"

//ConstantBuffer<FParticles> FluidParticles;

[numthreads(THREADS_X, THREADS_Y, THREADS_Z)]
void Compute(
	uint3 DispatchThreadId : SV_DispatchThreadID,
	uint GroupIndex : SV_GroupIndex )
{
    //for(int i = 0; i < FluidParticles.NumPositions; i++)
    //{
    //    float3 sub = float3(0.01, 0.01, 0.01);
    //    //FluidParticles.Positions[i] -= sub;
    //}
}